name: Python package

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-lint-unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run poe test
      - run: poetry run poe check
      - run: poetry run poe lint
      - run: poetry run poe types
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
      # Do not run in parallel to limit parallel integration tests stomping on each other
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: >
          poetry run pytest
          -m integration
          --cloud-api-key "${{ secrets.CLOUD_API_KEY }}"
          --enterprise-uri "https://test-api.lifecyclesolutions.ni.com" --enterprise-api-key "${{ secrets.ENTERPRISE_API_KEY }}"
